### PR TITLE
Upgrading material-dialogs version and adding checkBoxPrompt to picker

### PR DESCRIPTION
**Pull request by felipemartim**
I needed the checkbox prompt functionality, so I upgraded the library version and included the checkbox information on the callback of the picker.

Maybe it could be implemented in a more generic way, to all the callbacks. Tell me what you think about it.

### CODE REVIEW

**Comment by Noitidart** [comment]
This is super duper cool!! Thank you! I will check this out tomorrow, very excited to update the types and API with support for this! Thanks for your initial work!!

**Comment by Noitidart** [comment]
Taking a quick look, I think this would be an option we would add to `OptionsCommon` - https://github.com/aakashns/react-native-dialogs#type-optionscommon

We would add possibly two keys:

1. optional boolean option called `shouldShowCheckbox`? - falsy doesnt show
2. optional boolean option called `defaultCheckboxValue`? - only works if `shouldShowCheckbox` is truthy.

Or is it better to start options with same prefix, so people know its related. So `checkboxShouldShow` and `checkboxDefaultValue`?

And whenever this is set to true, the action promise resolves with boolean value of `isChecked`?

**Comment by Noitidart** [comment]
Hey @felipemartim when trying to merge this to here, then merge it to aakashns/react-native-dialogs I messed it up. It was not auto merging anymore.

They merged my patch-4 to master just the other day. May you please check out master from https://github.com/aakashns/react-native-dialogs and then submit these changes there please. I'll then join submit a PR to your PR to add in the types and javascript api support.

**Comment by felipemartim** [comment]
`May you please check out master from https://github.com/aakashns/react-native-dialogs and then submit these changes there please`

Sure! I also tried to create the PR directly into the original repository, but it wouldn't merge nicely. Later today I'll do that.

**Comment by Noitidart** [comment]
Thank you!

**Comment by Noitidart** [comment]
It seems that "checkbox" is supported by input type, plain type, and list type dialogs. Would be awesome if you could add it to all 3! :)

**Comment by felipemartim** [comment]
Sorry, I'm just too swamped right now, but I believe I can do that by next week.

**Comment by Noitidart** [comment]
No problem, thank you for your update!!

**Comment by Noitidart** [comment]
Hey @felipemartim - no pressure or rush, I was just excited to get this functionality it. Just curious on what your schedule looks like?

**Pull request merged**
